### ISSUE TITLE
List of games compatible with Xash3ds?

### ISSUE THREAD

**Issue by thanone2** [masterfeizz/Xash3DS#50]
Is there a list of games that (for the most part) work on this?

**Comment by XxSIBxX** [comment]
Theres a list for that here https://www.moddb.com/engines/xash3d-engine/features/xash3d-compatible-half-life-mods-with-a-custom-game-code

It might be a little inaccurate because Xash3DS uses a older port of the open source Xash3D engine and that list might be for a modern xash3d engine version but I don't know you'll have to experiment I guess.

**Comment by XxSIBxX** [comment]
This also could be a good resource to look at for this question
https://github.com/FWGS/xash3d/wiki/List-of-mods-which-work-on-Android-and-other-non-Windows-platforms-without-troubles

**Comment by thanone2** [comment]
ok, thanks!
